const hciProject = {
  id: "hci-project",
  name: "Husky Link",
  x: 42,
  y: 40,
  color: "#a8b07d",
  date: "Jan 2026",
  skills: ["Figma", "Hi-fi Prototyping", "Lo-fi prototyping", "Heuristic Evaluation"],
  why: "Northeastern Human-Computer Interaction (CS 2484) semester project",
  steps: [
    { title: "Identify the Problem", description: "Given the semester theme 'Northeastern University students’ loneliness' we were tasked to design an interface that alleviates this issue. Our group chose to specifically target students who were abroad anytime during their college experience." },
    { title: "Interview Process", description: "I conducted 2 separate interviews on students who did Northeastern's NUin program. Each interview was around 20 minutes long where I asked the following questions:", questions: [
  "Can you please say your major and where you spent your semester before coming to Boston.",
  "Describe to me your time before coming to the Boston campus (or coming back if co-op).",
  "What did it feel like coming to the Boston campus after being in a different environment for so long?",
  "Do you think upon re-entering campus your social life became better or worse?",
  "Did you find it easy to meet new people or make new friends on campus?",
  "Have you experienced loneliness since returning from where you previously were?",
  "What is different about the social life in Boston compared to what the social life was a semester ago for you?",
  "Do you think on-campus events made you feel more included?",
  "Did you find that clubs were easy to join / join back in?",
  "What was your dining hall experience like? Who were the kinds of people you preferred to eat with? Or did you just prefer to eat alone?",
  "Do you think your social life has had an impact on your mental health? If so, is that in a positive or negative way?",
  "Describe a time you felt like you fit in on campus.",
  "Was it easy to get to know people who might've started their time at Northeastern on a different campus?",
  "Do you think your academic commitments prevent you from socializing more? Do you wish this was not the case?",
  "Do you think there is a way for you to have a healthy balance of socializing with your peers while being productive in your academic work?",
  "On a daily basis do you think you talk to your peers in an academically oriented manner or do you feel like you can actually form a friendship with them outside of class?",
  ], afterText: "I then transcribed each of the interviews and added a summary to what the talk was about. "},
    { title: "POV Development", description: "After analyzing the interviews, I developed the following point of view statement:", quoteText: "Social and outgoing students who study abroad need casual, low-pressure reassurance, support, and reminders that their extraversion doesn't invalidate their feelings of loneliness because they often feel embarrassed when admitting they are struggling with connection." },
    { title: "Lo-fi Prototyping", description: "in progress" },
    { title: "Hi-fi Prototyping", description: "in progress" },
    { title: "Final Refinements", description: "in progress" },
  ],
};

export default hciProject;
