const hciProject = {
  id: "hci-project",
  name: "Husky Link",
  x: 42,
  y: 40,
  color: "#a8b07d",
  date: "Jan 2026",
  skills: ["Figma", "Hi-fi Prototyping", "Lo-fi prototyping", "Heuristic Evaluation"],
  why: "Northeastern Human-Computer Interaction (CS 2484) semester project",
  steps: [
    { title: "Identify the Problem", description: "Given the semester theme 'Northeastern University students’ loneliness' we were tasked to design an interface that alleviates this issue. Our group chose to specifically target students who were abroad anytime during their college experience. We discovered that many pre-existing solutions like Instagram, Snapchat, school clubs, study groups, all have some sort of flaw that hindered interaction amongst students." },
    { title: "Interview Process", description: "I conducted 2 separate interviews on students who did Northeastern's NUin program. Each interview was around 20 minutes long. Some core questions I asked:", questions: [
  "Describe to me your time before coming to the Boston campus (or coming back if co-op).",
  "What did it feel like coming to the Boston campus after being in a different environment for so long?",
  "Do you think upon re-entering campus your social life became better or worse?",
  "Did you find it easy to meet new people or make new friends on campus?",
  "What is different about the social life in Boston compared to what the social life was a semester ago for you?",
  "What was your dining hall experience like? Who were the kinds of people you preferred to eat with? Or did you just prefer to eat alone?",
  "Do you think your social life has had an impact on your mental health? If so, is that in a positive or negative way?",
  "Was it easy to get to know people who might've started their time at Northeastern on a different campus?",
  "Do you think your academic commitments prevent you from socializing more? Do you wish this was not the case?",
  "Do you think there is a way for you to have a healthy balance of socializing with your peers while being productive in your academic work?",
  ], afterText: "I then transcribed each of the interviews and added a summary to what the talk was about. "},
    { title: "POV Development", content: [ {text: "After analyzing the interviews, our group reviewed our stakeholders and the types of people who might be affected by our interface. I personally did NUin students, Student organizations trying to build global communities, and on-campus staff." }, 
      {quote: "Social and outgoing students who study abroad need casual, low-pressure reassurance, support, and reminders that their extraversion doesn't invalidate their feelings of loneliness because they often feel embarrassed when admitting they are struggling with connection." },
      ]},
    { title: "Task Analysis", description: "We narrowed down the painpoints on our stakeholders and came up with some tasks that help align with the issues that students are experiencing. We came up with the following:" , 
      questions: [ "Talking to a new person in class", "Admit loneliness to a peer", 
        "Schedule time for socializing", 
        "Posting on social media to share moments with friends", 
        "Seek formal mental health support", "Messaging a friend with time-zone differences", 
        "Connecting with a new person online", 
        "Comforting someone who is lonely (through online forum)" ],
        afterText: "We then created a hierarchical task diagram for each task which would later help us develop our lo-fi prototype "},
    { title: "Lo-fi Prototyping", content: [{text: "We each created a storyboard which drew from our POV statement. "},{image: "images/hci-storyboard.png"},
      {text: "Afterwards we created a lo-fi prototyped frame based off of our tasks"}
    ] },
    { title: "Hi-fi Prototyping", description: "in progress" },
    { title: "Final Refinements", description: "in progress" },
  ],
};

export default hciProject;
